version: "3.7"

services:
  backend:
    build:
      context: backend
      target: backend
    expose:
      - "8000"
    networks:
      pethelp:
        aliases:
          - backend
  frontend:
    build:
      context: frontend
      target: production-stage
    expose:
        - "80"
    ports:
        - "${HTTP_PORT}:80"
    networks:
      pethelp:
        aliases:
          - frontend
networks:
  pethelp:
