# Generated by Django 3.0.4 on 2020-03-21 15:54

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import pet_help.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('type', enumfields.fields.EnumField(enum=pet_help.models.HelpType, max_length=20)),
                ('description', models.CharField(max_length=1024)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('type', enumfields.fields.EnumField(enum=pet_help.models.HelpType, max_length=20)),
                ('description', models.CharField(max_length=1024)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=50)),
                ('emergency_contact_email', models.CharField(max_length=150)),
                ('image', models.TextField()),
                ('registered_at', models.DateField()),
                ('last_login', models.DateField()),
                ('virtual', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='pet_help.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='pet_help.User')),
                ('related_help_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_messages', to='pet_help.HelpOffer')),
                ('related_help_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_messages', to='pet_help.HelpRequest')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='pet_help.User')),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='pet_help.User'),
        ),
        migrations.AddField(
            model_name='helpoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_offers', to='pet_help.User'),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', enumfields.fields.EnumField(enum=pet_help.models.AnimalType, max_length=50)),
                ('image', models.TextField()),
                ('current_address', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1024)),
                ('care_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cared_animals', to='pet_help.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='pet_help.User')),
            ],
        ),
    ]
