# Generated by Django 3.0.4 on 2020-04-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_help", "0003_user_email_verified"),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="current_address",),
        migrations.RemoveField(model_name="animal", name="current_address_lat",),
        migrations.RemoveField(model_name="animal", name="current_address_lng",),
        migrations.AddField(
            model_name="helpoffer",
            name="address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="helpoffer",
            name="address_lat",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="helpoffer",
            name="address_lng",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="address_lat",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="address_lng",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
