name: CI for backend

on:
  push:
    paths:
    - 'backend/**'
  pull_request:
    paths:
    - 'backend/**'

env:
  working-directory: ./backend

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      
      - name: Linting
        uses: lgeiger/black-action@v1
        with:
          args: ". --check --line-length 99"
        working-directory: ${{ env.working-directory }}

  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        
      - name: Build image
        run: docker build . -f Dockerfile
        working-directory: ${{ env.working-directory }}
