name: CI for backend

on:
  push:
    paths:
    - 'backend/**'
  pull_request:
    paths:
    - 'backend/**'

env:
  working-directory: ./backend

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Check formatting rules with black
        uses: lgeiger/black-action@master
        with:
          args: ". --check --line-length 99"
        
      - name: Build image
        run: docker build . -f Dockerfile
        working-directory: ${{ env.working-directory }}
