name: CI for frontend

on:
  push:
    paths:
    - 'frontend/**'
  pull_request:
    paths:
    - 'frontend/**'

jobs:
  integration:
    runs-on: ubuntu-latest

    env:
      working-directory: ./frontend

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Install node using nvm
        uses: dcodeIO/setup-node-nvm@v3.0.0
        with:
          node-version: 12.16.1

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Linting
        run: npm run lint
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.working-directory }}