name: CI for frontend

on:
  push:
    paths:
    - 'frontend/**'
  pull_request:
    paths:
    - 'frontend/**'

env:
  working-directory: ./frontend

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Install node using nvm
        uses: dcodeIO/setup-node-nvm@v4.0.0
        with:
          node-version: 12.16.2

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Linting
        run: npm run lint
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.working-directory }}

  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        
      - name: Build image
        run: docker build . -f Dockerfile
        working-directory: ${{ env.working-directory }}
